blank_issues_enabled: false
contact_links:
  - name: GitHub Community of Practice
  - url: https://github.com/orgs/github/projects/1483#column-10308198
  - about: Create resources, share expertise, and serve as a liaison to product and engineering
